// Generated by CoffeeScript 1.6.2
/*
Sticky Elements Shortcut for jQuery Waypoints - v2.0.4
Copyright (c) 2011-2014 Caleb Troughton
Dual licensed under the MIT license and GPL license.
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
*/


(function() {
  (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      return define(['jquery', 'waypoints'], factory);
    } else {
      return factory(root.jQuery);
    }
  })(this, function(jQuery) {
    var defaults, wrap;

    defaults = {
      wrapper: '<div class="sticky-wrapper" />',
      stuckClass: 'stuck'
    };
    wrap = function(jQueryelements, options) {
      jQueryelements.wrap(options.wrapper);
      return jQueryelements.parent();
    };
    jQuery.waypoints('extendFn', 'sticky', function(opt) {
      var jQuerywrap, options, originalHandler;

      options = jQuery.extend({}, jQuery.fn.waypoint.defaults, defaults, opt);
      jQuerywrap = wrap(this, options);
      originalHandler = options.handler;
      options.handler = function(direction) {
        var jQuerysticky, shouldBeStuck;

        jQuerysticky = jQuery(this).children(':first');
        shouldBeStuck = direction === 'down' || direction === 'right';
        jQuerysticky.toggleClass(options.stuckClass, shouldBeStuck);
        jQuerywrap.height(shouldBeStuck ? jQuerysticky.outerHeight() : '');
        if (originalHandler != null) {
          return originalHandler.call(this, direction);
        }
      };
      jQuerywrap.waypoint(options);
      return this.data('stuckClass', options.stuckClass);
    });
    return jQuery.waypoints('extendFn', 'unsticky', function() {
      this.parent().waypoint('destroy');
      this.unwrap();
      return this.removeClass(this.data('stuckClass'));
    });
  });

}).call(this);