sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - hhvm

env:
  global:
    - THEME_DIR=./web/app/themes/theagsc/


before_install:
    - apt-get install php-pear
    - pear install PHP_CodeSniffer
    - apt-get install -y nodejs npm
    - npm install --global bower gulp

install:
      - composer install --no-dev --no-scripts --quiet --optimize-autoloader
      - cd $THEME_DIR
      - npm install --devDependencies --silent --no-spin
      - bower install
      - gulp --production

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - bower_components
    - node_modules

script:
  - cd $TRAVIS_BUILD_DIR
  - phpcs --standard=ruleset.xml --extensions=php --ignore=web/wp/,web/app/plugins/,vendor/ -n -s .
